routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate');



Route::resource('artTypes', 'ArtTypesController');

Route::resource('userProfiles', 'UserProfileController');

Route::resource('galleries', 'GalleryController');

Route::resource('artworks', 'ArtworkController');

Route::resource('artists', 'ArtistController');

Route::resource('users', 'UserController');

Route::resource('galleryArtists', 'GalleryArtistController');

app/Models/UserProfile.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="UserProfile",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="user_id",
 *          description="user_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="mobile",
 *          description="mobile",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="location",
 *          description="location",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="profession",
 *          description="profession",
 *          type="string"
 *      )
 * )
 */
class UserProfile extends Model
{
    use SoftDeletes;

    public $table = 'user_profiles';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'user_id',
        'mobile',
        'location',
        'profession',
        'pricerange'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'user_id' => 'integer',
        'mobile' => 'string',
        'location' => 'string',
        'profession' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function user()
    {
        return $this->belongsTo(\App\Models\User::class);
    }
}

app/Http/Controllers/UserProfileController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\UserProfileDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateUserProfileRequest;
use App\Http\Requests\UpdateUserProfileRequest;
use App\Repositories\UserProfileRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class UserProfileController extends AppBaseController
{
    /** @var  UserProfileRepository */
    private $userProfileRepository;

    public function __construct(UserProfileRepository $userProfileRepo)
    {
        $this->userProfileRepository = $userProfileRepo;
    }

    /**
     * Display a listing of the UserProfile.
     *
     * @param UserProfileDataTable $userProfileDataTable
     * @return Response
     */
    public function index(UserProfileDataTable $userProfileDataTable)
    {
        return $userProfileDataTable->render('user_profiles.index');
    }

    /**
     * Show the form for creating a new UserProfile.
     *
     * @return Response
     */
    public function create()
    {
        return view('user_profiles.create');
    }

    /**
     * Store a newly created UserProfile in storage.
     *
     * @param CreateUserProfileRequest $request
     *
     * @return Response
     */
    public function store(CreateUserProfileRequest $request)
    {
        $input = $request->all();

        $userProfile = $this->userProfileRepository->create($input);

        Flash::success('User Profile saved successfully.');

        return redirect(route('userProfiles.index'));
    }

    /**
     * Display the specified UserProfile.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $userProfile = $this->userProfileRepository->findWithoutFail($id);

        if (empty($userProfile)) {
            Flash::error('User Profile not found');

            return redirect(route('userProfiles.index'));
        }

        return view('user_profiles.show')->with('userProfile', $userProfile);
    }

    /**
     * Show the form for editing the specified UserProfile.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $userProfile = $this->userProfileRepository->findWithoutFail($id);

        if (empty($userProfile)) {
            Flash::error('User Profile not found');

            return redirect(route('userProfiles.index'));
        }

        return view('user_profiles.edit')->with('userProfile', $userProfile);
    }

    /**
     * Update the specified UserProfile in storage.
     *
     * @param  int              $id
     * @param UpdateUserProfileRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateUserProfileRequest $request)
    {
        $userProfile = $this->userProfileRepository->findWithoutFail($id);

        if (empty($userProfile)) {
            Flash::error('User Profile not found');

            return redirect(route('userProfiles.index'));
        }

        $userProfile = $this->userProfileRepository->update($request->all(), $id);

        Flash::success('User Profile updated successfully.');

        return redirect(route('userProfiles.index'));
    }

    /**
     * Remove the specified UserProfile from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $userProfile = $this->userProfileRepository->findWithoutFail($id);

        if (empty($userProfile)) {
            Flash::error('User Profile not found');

            return redirect(route('userProfiles.index'));
        }

        $this->userProfileRepository->delete($id);

        Flash::success('User Profile deleted successfully.');

        return redirect(route('userProfiles.index'));
    }
}

resources/views/user_profiles/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            User Profile
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'userProfiles.store']) !!}

                        @include('user_profiles.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user_profiles/datatables_actions.blade.php
{!! Form::open(['route' => ['userProfiles.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('userProfiles.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('userProfiles.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/user_profiles/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            User Profile
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($userProfile, ['route' => ['userProfiles.update', $userProfile->id], 'method' => 'patch']) !!}

                        @include('user_profiles.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/user_profiles/fields.blade.php
<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::number('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Mobile Field -->
<div class="form-group col-sm-6">
    {!! Form::label('mobile', 'Mobile:') !!}
    {!! Form::text('mobile', null, ['class' => 'form-control']) !!}
</div>

<!-- Location Field -->
<div class="form-group col-sm-6">
    {!! Form::label('location', 'Location:') !!}
    {!! Form::text('location', null, ['class' => 'form-control']) !!}
</div>

<!-- Profession Field -->
<div class="form-group col-sm-6">
    {!! Form::label('profession', 'Profession:') !!}
    {!! Form::text('profession', null, ['class' => 'form-control']) !!}
</div>

<!-- Pricerange Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pricerange', 'Pricerange:') !!}
    {!! Form::number('pricerange', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('userProfiles.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/user_profiles/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">User Profiles</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('userProfiles.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('user_profiles.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/user_profiles/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            User Profile
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('user_profiles.show_fields')
                    <a href="{!! route('userProfiles.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user_profiles/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $userProfile->id !!}</p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{!! $userProfile->user_id !!}</p>
</div>

<!-- Mobile Field -->
<div class="form-group">
    {!! Form::label('mobile', 'Mobile:') !!}
    <p>{!! $userProfile->mobile !!}</p>
</div>

<!-- Location Field -->
<div class="form-group">
    {!! Form::label('location', 'Location:') !!}
    <p>{!! $userProfile->location !!}</p>
</div>

<!-- Profession Field -->
<div class="form-group">
    {!! Form::label('profession', 'Profession:') !!}
    <p>{!! $userProfile->profession !!}</p>
</div>

<!-- Pricerange Field -->
<div class="form-group">
    {!! Form::label('pricerange', 'Pricerange:') !!}
    <p>{!! $userProfile->pricerange !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $userProfile->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $userProfile->updated_at !!}</p>
</div>

resources/views/user_profiles/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection