routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate');



Route::resource('artTypes', 'ArtTypesController');

Route::resource('userProfiles', 'UserProfileController');

Route::resource('galleries', 'GalleryController');

Route::resource('artworks', 'ArtworkController');

Route::resource('artists', 'ArtistController');

Route::resource('users', 'UserController');

Route::resource('galleryArtists', 'GalleryArtistController');

app/Http/Controllers/ArtTypesController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ArtTypesDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateArtTypesRequest;
use App\Http\Requests\UpdateArtTypesRequest;
use App\Repositories\ArtTypesRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class ArtTypesController extends AppBaseController
{
    /** @var  ArtTypesRepository */
    private $artTypesRepository;

    public function __construct(ArtTypesRepository $artTypesRepo)
    {
        $this->artTypesRepository = $artTypesRepo;
    }

    /**
     * Display a listing of the ArtTypes.
     *
     * @param ArtTypesDataTable $artTypesDataTable
     * @return Response
     */
    public function index(ArtTypesDataTable $artTypesDataTable)
    {
        return $artTypesDataTable->render('art_types.index');
    }

    /**
     * Show the form for creating a new ArtTypes.
     *
     * @return Response
     */
    public function create()
    {
        return view('art_types.create');
    }

    /**
     * Store a newly created ArtTypes in storage.
     *
     * @param CreateArtTypesRequest $request
     *
     * @return Response
     */
    public function store(CreateArtTypesRequest $request)
    {
        $input = $request->all();

        $artTypes = $this->artTypesRepository->create($input);

        Flash::success('Art Types saved successfully.');

        return redirect(route('artTypes.index'));
    }

    /**
     * Display the specified ArtTypes.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $artTypes = $this->artTypesRepository->findWithoutFail($id);

        if (empty($artTypes)) {
            Flash::error('Art Types not found');

            return redirect(route('artTypes.index'));
        }

        return view('art_types.show')->with('artTypes', $artTypes);
    }

    /**
     * Show the form for editing the specified ArtTypes.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $artTypes = $this->artTypesRepository->findWithoutFail($id);

        if (empty($artTypes)) {
            Flash::error('Art Types not found');

            return redirect(route('artTypes.index'));
        }

        return view('art_types.edit')->with('artTypes', $artTypes);
    }

    /**
     * Update the specified ArtTypes in storage.
     *
     * @param  int              $id
     * @param UpdateArtTypesRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateArtTypesRequest $request)
    {
        $artTypes = $this->artTypesRepository->findWithoutFail($id);

        if (empty($artTypes)) {
            Flash::error('Art Types not found');

            return redirect(route('artTypes.index'));
        }

        $artTypes = $this->artTypesRepository->update($request->all(), $id);

        Flash::success('Art Types updated successfully.');

        return redirect(route('artTypes.index'));
    }

    /**
     * Remove the specified ArtTypes from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $artTypes = $this->artTypesRepository->findWithoutFail($id);

        if (empty($artTypes)) {
            Flash::error('Art Types not found');

            return redirect(route('artTypes.index'));
        }

        $this->artTypesRepository->delete($id);

        Flash::success('Art Types deleted successfully.');

        return redirect(route('artTypes.index'));
    }
}

resources/views/art_types/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Art Types
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'artTypes.store']) !!}

                        @include('art_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/art_types/datatables_actions.blade.php
{!! Form::open(['route' => ['artTypes.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('artTypes.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('artTypes.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/art_types/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Art Types
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($artTypes, ['route' => ['artTypes.update', $artTypes->id], 'method' => 'patch']) !!}

                        @include('art_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/art_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('artTypes.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/art_types/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Art Types</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('artTypes.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('art_types.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/art_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Art Types
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('art_types.show_fields')
                    <a href="{!! route('artTypes.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/art_types/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $artTypes->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $artTypes->name !!}</p>
</div>

resources/views/art_types/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection